apiVersion: v1
kind: Service
metadata:
  name: ms-getAttemptQuizes-service
spec:
  type: ClusterIP
  selector:
    app: ms-getAttemptQuizes-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8006
