apiVersion: v1
kind: Service
metadata:
  name: ms-updateQuestion-service
spec:
  type: ClusterIP
  selector:
    app: ms-updateQuestion-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8016
