apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpj-backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fpjbe
  template:
    metadata:
      labels:
        app: fpjbe
    spec:
      nodeSelector:
        role: backend
      containers:
      - name: fpjbe
        image: djtoler/fp-back-blue-useast1:latest
        ports:
        - containerPort: 8000
        env:  # Environment variables are specified here, within the container spec
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog-secret
                key: apiKey
          - name: DD_APP_KEY
            valueFrom:
              secretKeyRef:
                name: datadog-secret
                key: appKey
