apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpj-frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fpjfe2
  template:
    metadata:
      labels:
        app: fpjfe2
    spec:
      containers:
      - name: fpjfe2
        image: djtoler/fp-front-blue-useast1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000