apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: fpj-frontend-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fpj-frontend-app
  minReplicas: 2
  maxReplicas: 5  
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
